name = "advent_of_code"
version = "0.1.0"
# repository = { type = "github", user = "my-user", repo = "advent_of_code" }

[dependencies]
gleam_stdlib = "~> 0.18"
gleam_otp = "~> 0.3"
gleam_erlang = "~> 0.4"
snag = "~> 0.2"

[dev-dependencies]
gleeunit = "~> 0.4"
# gleam_should_assertions = "~> 0.2"
